### ISSUE TITLE
Cucumber task fails in notification routine

### ISSUE THREAD

**Issue by astery** [guard/guard-cucumber#22]
To reproduce:

    git clone https://github.com/astery/video-vault.git
    cd video-vault
    git checkout b04ffd9
    ln -s database.yml.example config/database.yml
    sed -i -r 's/, :notification => false//' Guardfile # Enable notifications
    bundle install
    bundle exec guard

I have a following [error output](http://pastebin.com/vPkADXBi).

Arguments of `self.notify(msg, options = {})` in `/home/user/.gem/ruby/2.0.0/gems/guard-compat-1.2.1/lib/guard/compat/plugin.rb`:

    ["a regular user \"*Jack*\"", {:title=>nil, :image=>:pending}]

`a regular user "Jack"` is background section step.

**Comment by astery** [comment]
This, situation can be fixed with adding before_background hook:

    def before_background(el)
      @feature_name = el.name
    end

But I don't sure if it's the best one.

**Comment by e2** [comment]
Thank you *very* much for such a detailed report (I really appreciate it!) - and for the repo (I would've never guessed it was because of a failing background scenario).

I've released 1.5.4 - let me know if you have any other issues.

**Comment by astery** [comment]
Thank you too for your contribution.
