### ISSUE TITLE
Guard hangs when running cucumber tests

### ISSUE THREAD

**Issue by andrewhavens** [guard/guard-cucumber#26]
I'm running into a strange issue where guard hangs (until I press `Control+C`) after running the cucumber test suite. A similar issue occurs with rspec. I have tried running both rspec and cucumber individually in my Guardfile and it seems to affect both in slightly different ways.

This is a new Rails 4 application and I am using Spring. I am wondering if guard-cucumber and guard-rspec's Spring support is up-to-date with what is now the Rails version of Spring. I don't have much evidence...it's just a guess. I can successfully run `bin/rspec` and `bin/cucumber` without issues.

**Comment by e2** [comment]
I won't have time to reply - basically, Spring depends on an ancient version of Listen. There's work to fix this, but it's ongoing. There's a spring-watcher-listen gem, which may work, there's an unreleased fix in Celluloid. There's an upcoming version of Listen that works without Celluloid (Listen 3.x branch) - and will likely work fine, but needs some testing before it's released.

I'd seriously suggest switching from Spring to Zeus + Guard::Zeus until this is fixed.

Sorry, but that's all I have time for.

**Comment by andrewhavens** [comment]
@e2 Ah, okay. Thanks for the info. That's helpful to know. I searched all over and didn't find any mention of this.

**Comment by andrewhavens** [comment]
Turns out my problem had nothing to do with spring. Spring and guard-cucumber work fine. My issue was trying to run guard under tmux and guard would hang when it tried to display a notification. [I submitted the issue with guard](https://github.com/guard/guard/issues/770).
